- hosts: linux
  become: yes
  tasks:
  - name: create fact directory
    file:
      path: /etc/ansible/facts.d
      recurse: yes
      state: directory
  - name: copy script to facts directory
    template:
      src: /root/playbooks/datetime.sh.j2
      dest: /etc/ansible/facts.d/date_time.fact
      mode: 0755
  - name: reload ansible fact
    setup: filter=ansible_local
  - name: print custom fact
    debug:
      msg: " custom fact is {{ ansible_local.date_time }}"
