- hosts: linux
  tasks:
  - name: print file content
    command: cat testfile
    register: filecontent
  - debug: msg="File is empty"
    when: filecontent.stdout==""
  - debug: msg="File is not empty. conten is:  {{ filecontent.stdout }}"
    when: filecontent.stdout!=""
